packages:
  - packages/*

allowBuilds:
  "@vscode/vsce-sign": false
  dprint: true
  keytar: false

blockExoticSubdeps: true
minimumReleaseAge: 1440

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
